services:
  yvonnes-store-api:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

    ports:
      - "${FORWARD_APP_PORT-8000}:80"

    depends_on:
      meilisearch:
        condition: service_healthy
        restart: true
    command: /var/www/html/entrypoint.sh
    volumes:
      - ".:/var/www/html"
      - "/var/www/html/.git/"
    networks:
      - yvonnes_network

  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    environment:
      MEILI_NO_ANALYTICS: "${MEILISEARCH_NO_ANALYTICS:-false}"
      MEILI_MASTER_KEY: "${MEILISEARCH_KEY}"
    volumes:
      - "meilisearch_data:/meili_data"
    networks:
      - yvonnes_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--spider",
          "http://127.0.0.1:7700/health",
        ]
      retries: 3
      timeout: 5s
      start_period: 15s

networks:
  yvonnes_network:
    driver: bridge

volumes:
  db_data:
  meilisearch_data:
