name: Staging Deploy
on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_TOKEN}}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 300

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.digitalocean.com/drewl/yvonnes-store-api:stg
